#pragma once

#include <LWS/KeyCode.hpp>

#include <linux/input-event-codes.h>

#include <cstdint>

namespace LWS::internal
{
    constexpr KeyCode keyCodeFromLinux(uint32_t key)
    {
        switch (key)
        {
            case KEY_A:
                return KeyCode::A;
            case KEY_B:
                return KeyCode::B;
            case KEY_C:
                return KeyCode::C;
            case KEY_D:
                return KeyCode::D;
            case KEY_E:
                return KeyCode::E;
            case KEY_F:
                return KeyCode::F;
            case KEY_G:
                return KeyCode::G;
            case KEY_H:
                return KeyCode::H;
            case KEY_I:
                return KeyCode::I;
            case KEY_J:
                return KeyCode::J;
            case KEY_K:
                return KeyCode::K;
            case KEY_L:
                return KeyCode::L;
            case KEY_M:
                return KeyCode::M;
            case KEY_N:
                return KeyCode::N;
            case KEY_O:
                return KeyCode::O;
            case KEY_P:
                return KeyCode::P;
            case KEY_Q:
                return KeyCode::Q;
            case KEY_R:
                return KeyCode::R;
            case KEY_S:
                return KeyCode::S;
            case KEY_T:
                return KeyCode::T;
            case KEY_U:
                return KeyCode::U;
            case KEY_V:
                return KeyCode::V;
            case KEY_W:
                return KeyCode::W;
            case KEY_X:
                return KeyCode::X;
            case KEY_Y:
                return KeyCode::Y;
            case KEY_Z:
                return KeyCode::Z;
            case KEY_0:
                return KeyCode::Digit0;
            case KEY_1:
                return KeyCode::Digit1;
            case KEY_2:
                return KeyCode::Digit2;
            case KEY_3:
                return KeyCode::Digit3;
            case KEY_4:
                return KeyCode::Digit4;
            case KEY_5:
                return KeyCode::Digit5;
            case KEY_6:
                return KeyCode::Digit6;
            case KEY_7:
                return KeyCode::Digit7;
            case KEY_8:
                return KeyCode::Digit8;
            case KEY_9:
                return KeyCode::Digit9;
            case KEY_F1:
                return KeyCode::F1;
            case KEY_F2:
                return KeyCode::F2;
            case KEY_F3:
                return KeyCode::F3;
            case KEY_F4:
                return KeyCode::F4;
            case KEY_F5:
                return KeyCode::F5;
            case KEY_F6:
                return KeyCode::F6;
            case KEY_F7:
                return KeyCode::F7;
            case KEY_F8:
                return KeyCode::F8;
            case KEY_F9:
                return KeyCode::F9;
            case KEY_F10:
                return KeyCode::F10;
            case KEY_F11:
                return KeyCode::F11;
            case KEY_F12:
                return KeyCode::F12;
            case KEY_KP0:
                return KeyCode::Numpad0;
            case KEY_KP1:
                return KeyCode::Numpad1;
            case KEY_KP2:
                return KeyCode::Numpad2;
            case KEY_KP3:
                return KeyCode::Numpad3;
            case KEY_KP4:
                return KeyCode::Numpad4;
            case KEY_KP5:
                return KeyCode::Numpad5;
            case KEY_KP6:
                return KeyCode::Numpad6;
            case KEY_KP7:
                return KeyCode::Numpad7;
            case KEY_KP8:
                return KeyCode::Numpad8;
            case KEY_KP9:
                return KeyCode::Numpad9;
            case KEY_LEFT:
                return KeyCode::Left;
            case KEY_RIGHT:
                return KeyCode::Right;
            case KEY_UP:
                return KeyCode::Up;
            case KEY_DOWN:
                return KeyCode::Down;
            case KEY_HOME:
                return KeyCode::Home;
            case KEY_END:
                return KeyCode::End;
            case KEY_PAGEUP:
                return KeyCode::PageUp;
            case KEY_PAGEDOWN:
                return KeyCode::PageDown;
            case KEY_INSERT:
                return KeyCode::Insert;
            case KEY_DELETE:
                return KeyCode::Delete;
            case KEY_ENTER:
                return KeyCode::Enter;
            case KEY_ESC:
                return KeyCode::Escape;
            case KEY_TAB:
                return KeyCode::Tab;
            case KEY_BACKSPACE:
                return KeyCode::Backspace;
            case KEY_SPACE:
                return KeyCode::Space;
            case KEY_LEFTSHIFT:
                return KeyCode::LShift;
            case KEY_RIGHTSHIFT:
                return KeyCode::RShift;
            case KEY_LEFTCTRL:
                return KeyCode::LControl;
            case KEY_RIGHTCTRL:
                return KeyCode::RControl;
            case KEY_LEFTALT:
                return KeyCode::LAlt;
            case KEY_RIGHTALT:
                return KeyCode::RAlt;
            case KEY_LEFTMETA:
            case KEY_RIGHTMETA:
                return KeyCode::Win;
            case KEY_CAPSLOCK:
                return KeyCode::CapsLock;
            case KEY_NUMLOCK:
                return KeyCode::NumLock;
            case KEY_SCROLLLOCK:
                return KeyCode::ScrollLock;
            case KEY_KPPLUS:
                return KeyCode::NumpadAdd;
            case KEY_KPMINUS:
                return KeyCode::NumpadSubtract;
            case KEY_KPASTERISK:
                return KeyCode::NumpadMultiply;
            case KEY_KPSLASH:
                return KeyCode::NumpadDivide;
            case KEY_KPDOT:
                return KeyCode::NumpadDecimal;
            case KEY_KPENTER:
                return KeyCode::NumpadEnter;
            case KEY_COMMA:
                return KeyCode::Comma;
            case KEY_DOT:
                return KeyCode::Period;
            case KEY_SLASH:
                return KeyCode::Slash;
            case KEY_SEMICOLON:
                return KeyCode::Semicolon;
            case KEY_APOSTROPHE:
                return KeyCode::Quote;
            case KEY_LEFTBRACE:
                return KeyCode::LeftBracket;
            case KEY_RIGHTBRACE:
                return KeyCode::RightBracket;
            case KEY_BACKSLASH:
                return KeyCode::Backslash;
            case KEY_MINUS:
                return KeyCode::Minus;
            case KEY_EQUAL:
                return KeyCode::Equals;
            case KEY_GRAVE:
                return KeyCode::Tilde;
            case KEY_SYSRQ:
                return KeyCode::PrintScreen;
            case KEY_PAUSE:
                return KeyCode::Pause;
            default:
                return KeyCode::Unknown;
        }
    }
}  // namespace LWS::internal
